### ISSUE TITLE
Pipeline server client requests blocked by iboss

### ISSUE THREAD

**Issue by sbin149x** [dlstreamer/pipeline-server#109] opened 2022-04-27 07:18 UTC
I receive this warning when executing this command sudo ./docker/build.sh:

groups: cannot find name for group ID 109
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f4d715282b0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/jsonschema/
ERROR: Could not find a version that satisfies the requirement jsonschema[format_nongpl]==3.2.0 (from versions: none)
ERROR: No matching distribution found for jsonschema[format_nongpl]==3.2.0

I'm not sure abt the group ID 109. As for the connection, I've setup the proxies for docker.

**Comment by nnshah1** [comment] 2022-04-27 11:43
@sbin149x In addition to setting up proxies for docker runtime itself, you'll need to set up the http_proxy, https_proxy, HTTP_PROXY,HTTPS_PROXY environment variables. 

Can you check those as well?

**Comment by whbruce** [comment] 2022-04-27 17:33
You can ignore the message `groups: cannot find name for group ID 109`, this is related to using GPU for inference.

**Comment by sbin149x** [comment] 2022-05-09 02:10
Hi  @nnshah1, I already set up those proxies for environment and manage to build the docker. Thanks for the help.

**Comment by sbin149x** [comment] 2022-05-09 02:11
Oh okay thanks @whbruce

**Comment by sbin149x** [comment] 2022-05-09 04:12
After build the docker and run it, I execute ./vaclient/vaclient.sh list-pipelines on another terminal but got this error:

rbhesve@rbhesve-Tiger-Lake-Client-Platform:~/pipeline-server$ ./vaclient/vaclient.sh list-pipelines

Found /dev/dri/render entry - enabling for GPU
Found /dev/bus/usb - enabling for Intel(R) NCS2
Found /dev/snd - enabling microphone

Running Intel(R) DL Streamer Pipeline Server Image: 'dlstreamer-pipeline-server-gstreamer'
   Models: ''
   Pipelines: ''
   Framework: 'gstreamer'
   Environment: ''
   Volume Mounts: '-v /tmp:/tmp -v /dev/bus/usb:/dev/bus/usb '
   Mode: 'CUSTOM_ENTRYPOINT'
   Ports: ''
   Name: '""'
   Network: '--network host'
   Entrypoint: '--entrypoint python3'
   EntrypointArgs: '/home/pipeline-server/vaclient list-pipelines '
   User: '--user 1000'
   User Groups: '--group-add 109 --group-add audio --group-add users '
   Devices: '--device /dev/dri --device /dev/snd '
   Device CGroup Rule: '--device-cgroup-rule='c 189:* rmw''

Got unsuccessful status code: 404
iboss


        html,body {
            font-family: "Open Sans",â  Helvetica,â  Arial,â  sans-serif;
            height: 100%;
                        width: 100%;
                        margin: auto;
        }
        body {
            min-height: 400px;
        }
        #header {
            background: #dde0e2;
            padding: 15px;
            box-sizing: border-box;
            position: relative;
        }
        #footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            background: #6d7d8d;
            padding: 15px;
            text-align: right;
            font-size: 12px;
            color: #fff;
            box-sizing: border-box;
        }
        .center {
            max-width: 820px;
            margin: auto;
        }
        #content {
            min-height: 400px;
                        max-width: 60%;
                        margin: auto;
        }
        #ibLogo {
            height: 45px;
            background-repeat: no-repeat;
            background-image: url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MjMgMTM1LjciPgogIDxzdHlsZT4 KICAgIC5zdDB7ZmlsbDojMDEwMTAxO30gLnN0MXtmaWxsOiM1OTg2M0M7fQogIDwvc3R5bGU+CiAgPHBhdGggY2xhc3M9InN0MCIgZD0iTTI1LjQgMzguMUgwYzAtMTEuNiAxMi4yLTIyLjYgMjUuNC0yMi42djI yLjZ6Ii8+CiAgPHBhdGggY2xhc3M9InN0MSIgZD0iTTI1MC45IDI1Ljl2MjUuNmM5LjIgNi4yIDE1LjEgMTYuMSAxNS4xIDI3LjMgMCAxOC44LTE2LjggMzQtMzcuNiAzNC0yMC43IDAtMzcuNi0xNS4yLTM3LjY tMzQgMC0xMS4yIDYtMjEuMSAxNS4yLTI3LjNWMjUuOWMtMjIuMyA4LjQtMzggMjguOS0zOCA1Mi45IDAgMzEuNSAyNyA1NyA2MC40IDU3IDMzLjMgMCA2MC40LTI1LjUgNjAuNC01NyAwLTI0LTE1LjctNDQuNS0 zNy45LTUyLjl6Ii8+CiAgPHBhdGggY2xhc3M9InN0MCIgZD0iTTk4LjUgMjEuOGMtMTQuOCAwLTMwLjMgNi41LTM3LjMgMTRWMGgtMjN2NzguN2MwIDM0LjQgMjQuMiA1NyA2MC40IDU3IDMzLjMgMCA2MC40LTI 1LjUgNjAuNC01N3MtMjcuMi01Ni45LTYwLjUtNTYuOXptMCA5MWMtMjAuNyAwLTM3LjYtMTUuMi0zNy42LTM0IDAtMjAuNiAxNi44LTM0IDM3LjYtMzQgMjAuNyAwIDM3LjYgMTUuMiAzNy42IDM0cy0xNi45IDM 0LTM3LjYgMzR6Ii8+CiAgPHBhdGggY2xhc3M9InN0MSIgZD0iTTIyOC41IDE5LjVjLTQgMC03LjkuMy0xMS43Ljl2NjMuM2gyMy4zVjIwLjRjLTMuNy0uNi03LjYtLjktMTEuNi0uOSIvPgogIDxwYXRoIGNsYXN zPSJzdDAiIGQ9Ik0zNTguNyAxMTEuMWgtNjF2MjIuNWg2My44YzEzLjUgMCAzMS40LTYuNyAzMS40LTI5LjIgMC0yMC41LTEzLjQtMjctMjIuNy0zMC0xMy43LTQuMy0zMC41LTkuNi00MC4zLTEyLjgtMy44LTE uMi03LjUtMi42LTcuNS03LjUgMC02LjIgNi4zLTYuNyAxMS4zLTYuN2g1M1YyNC45aC01NS41Yy0xNi43IDAtMzMuOCA3LjktMzMuOCAyOS4zIDAgMjEuMiAxMy41IDI2LjMgMjQuMSAyOS43IDE0LjIgNC41IDI 1LjQgOC4xIDM5LjEgMTIuNSAzLjUgMS4xIDcuMyAzLjEgNy4zIDcuNCAwIDYuNS02LjQgNy4zLTkuMiA3LjNtMTA2LjEgMGgtNjF2MjIuNWg2My44YzEzLjUgMCAzMS40LTYuNyAzMS40LTI5LjIgMC0yMC41LTE zLjQtMjctMjIuNy0zMC0xMy43LTQuMy0zMC41LTkuNi00MC4zLTEyLjgtMy44LTEuMi03LjUtMi42LTcuNS03LjUgMC02LjIgNi4zLTYuNyAxMS4zLTYuN2g1M1YyNC45aC01NS41Yy0xNi43IDAtMzMuOCA3Ljk tMzMuOCAyOS4zIDAgMjEuMiAxMy41IDI2LjMgMjQuMSAyOS43IDE0LjEgNC41IDI1LjQgOC4xIDM5LjEgMTIuNSAzLjUgMS4xIDcuMyAzLjEgNy4zIDcuNCAwIDYuNS02LjMgNy4zLTkuMiA3LjNtLTQzOS40LTY ySDBWMTEwYzAgMTEuNiAxMi4yIDIyLjYgMjUuNCAyMi42VjQ5LjF6bTQ3NS0xMi45YzAtMiAuNS0zLjkgMS41LTUuNiAxLTEuOCAyLjQtMy4xIDQuMS00LjEgMS44LTEgMy42LTEuNSA1LjctMS41IDIgMCAzLjk uNSA1LjYgMS41IDEuOCAxIDMuMSAyLjQgNC4xIDQuMSAxIDEuOCAxLjUgMy42IDEuNSA1LjcgMCAyLS41IDMuOC0xLjUgNS42LTEgMS43LTIuMyAzLjEtNC4xIDQuMi0xLjggMS0zLjcgMS42LTUuOCAxLjYtMi4 xIDAtNC0uNS01LjctMS42LTEuOC0xLTMuMS0yLjQtNC4xLTQuMi0uOC0xLjktMS4zLTMuNy0xLjMtNS43em0xLjYgMGMwIDEuNy40IDMuNCAxLjMgNC45LjkgMS41IDIuMSAyLjcgMy42IDMuNiAxLjUuOSAzLjE gMS4zIDQuOCAxLjMgMS43IDAgMy40LS40IDQuOC0xLjMgMS41LS45IDIuNy0yIDMuNi0zLjUuOS0xLjUgMS4zLTMuMSAxLjMtNC45IDAtMS43LS40LTMuNC0xLjMtNC44LS45LTEuNS0yLTIuNy0zLjUtMy42LTE uNS0uOS0zLjEtMS4zLTQuOS0xLjMtMS43IDAtMy40LjQtNC44IDEuMy0xLjUuOS0yLjcgMi0zLjYgMy41LS44IDEuNC0xLjMgMy0xLjMgNC44em0xNC4zLTIuOGMwIC44LS4yIDEuNS0uNiAyLjEtLjQuNi0xIDE uMS0xLjggMS40bDMuNiA1LjlINTE1bC0zLjEtNS4zaC0ydjUuM2gtMi4yVjI5LjVoMy45YzEuNyAwIDIuOS4zIDMuNyAxIC42LjYgMSAxLjYgMSAyLjl6bS02LjUgMi4zaDEuNmMuOCAwIDEuNC0uMiAxLjktLjY uNS0uNC43LS45LjctMS42IDAtLjgtLjItMS4zLS42LTEuNi0uNC0uMy0xLjEtLjUtMi0uNWgtMS42djQuM3oiLz4KPC9zdmc+');
        }
        .button {
                        background-color: #7ab071;
            border: none;
            text-align: center;
            font-size: 22px;
            padding: 10px;
            width: 270px;
            transition: all 0.5s;
            cursor: pointer;
            max-width: 100%;
            display: block;
            box-sizing: border-box;
                        color: #ffffff;
        }
        .button span {
            cursor: pointer;
            display: inline-block;
            position: relative;
            transition: 0.5s;
        }
        .button span:after {
            content: '\00bb';
            opacity: 0;
            top: 0;
            right: -20px;
            transition: 0.5s;
        }
        .button:hover span {
            padding-right: 25px;
        }
        .button:hover span:after {
            opacity: 1;
            right: 0;
        }
                .learnMore {
                        font-size: 16px;
                        font-weight: none;
                        color: #7ab071;
            width: 270px;
            transition: all 0.5s;
            cursor: pointer;
            max-width: 100%;
            display: block;
            box-sizing: border-box;
        }
        .learnMore span {
            cursor: pointer;
            display: inline-block;
            position: relative;
            transition: 0.5s;
        }
        .learnMore span:after {
            content: '\00bb';
            opacity: 0;
            top: 0;
            right: -20px;
            transition: 0.5s;
        }
        .learnMore:hover span {
            padding-right: 25px;
        }
        .learnMore:hover span:after {
            opacity: 1;
            right: 0;
        }
                .spaceLarge {
                        margin: 50px;
                }
                .space {
                        margin: 25px;
                }
        #message {
            font-size: 80px;
            font-weight: bold;
            color: #2d4797;
        }
                #subMessage {
                        font-size: 28px;
                        font-weight: bold;
                        color: #787878
                }
                #errorCode {
                        font-size: 22px;
                        font-weight: none;
                        color: #aaaaaa;
                }











        NOT FOUND


                The page you are looking for cannot be found at this time.



                Error Code: 404


    Go to iboss Cloud

        Learn More at iboss.com



    Â© 2004 - 2017 iboss, Inc. All rights reserved. All trademarks and registered trademarks on this website are the property of their respective owners.


    document.getElementById('year').innerHTML = new Date().getFullYear();
Got empty response retrieving pipelines

**Comment by whbruce** [comment] 2022-05-09 16:28
Please update title to indicate this is a runtime, not build time, issue.
I believe this is due to iboss configuration, please try a curl command `curl localhost:8080/pipelines`

**Comment by sbin149x** [comment] 2022-05-19 03:53
I did try the curl command but when run back the ./vaclient/vaclient.sh list-pipelines still got the same output.
Did I do it wrongly? 

rbhesve@rbhesve-NUC11PAHi7:~/pipeline-server$ curl localhost:8080/pipelines
[
  {
    "description": "Decode Pipeline",
    "name": "video_decode",
    "type": "GStreamer",
    "version": "app_dst"
  },
  {
    "description": "Environmental sound detection based on Aclnet",
    "name": "audio_detection",
    "parameters": {
      "properties": {
        "bus-messages": {
          "default": false,
          "description": "Prints GstBus messages as logger info",
          "type": "boolean"
        },
        "detection-properties": {
          "element": {
            "format": "element-properties",
            "name": "detection"
          }
        },
        "device": {
          "element": "detection",
          "type": "string"
        },
        "output-buffer-duration": {
          "default": 100000000,
          "element": "audiomixer",
          "type": "integer"
        },
        "post-messages": {
          "element": "level",
          "type": "boolean"
        },
        "sliding-window": {
          "default": 0.2,
          "element": "detection",
          "type": "number"
        },
        "threshold": {
          "element": "detection",
          "type": "number"
        }
      },
      "type": "object"
    },
    "type": "GStreamer",
    "version": "environment"
  },

<SNIP>

**Comment by whbruce** [comment] 2022-05-26 22:43
Iboss thinks pipeline server client is making a dangerous request so blocks it. Contact me directly and we'll try and resolve it.

One idea - specify server using fqdn (e.g. my-server.corp.com).

```
vaclient/vaclient.sh --server-address http://my-server.corp.com:8080 list-pipelines
```

**Comment by whbruce** [comment] 2022-08-20 00:39
I have confirmed that specifying server address as fqdn avoids iboss error. Closing.

**Closed by whbruce** 2022-08-20 00:39 UTC
Labels: question
